name: FTP Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@a4586c39157e8a431de9d4eafdba6bd71f98fb60
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --remote-root /htdocs/
          local-dir: .
